# References:
# 1. https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# 2. https://circleci.com/docs/2.0/building-docker-images/
#

version: 2

jobs:
  build:
    working_directory: /build
    docker:
      - image: centos:6.9
        environment: &env
          NAME: bmo # named this for historical reasons
          PERL_DIR: /opt/vanilla-perl
          PERL: /opt/vanilla-perl/bin/perl
          SYSTEM_PERL: /usr/bin/perl
          CARTON: /opt/vanilla-perl/bin/carton
          PERL5LIB: /build/centos6/local/lib/perl5
          PATH: /build/bin:/usr/local/bin:/usr/bin:/bin
    steps:
      - checkout
      - run:
          name: install rpms
          command: |
            rpm -qa --queryformat '/^%{NAME}$/ d\n' > rpm_fix.sed
            sed -f rpm_fix.sed /build/centos6/rpm_list > /rpm_list.clean
            yum -q -y install epel-release
            yum -q -y install `cat /rpm_list.clean`
      - run:
          name: download some tools
          command: |
            curl -L https://raw.github.com/tokuhirom/Perl-Build/master/perl-build \
              > /usr/local/bin/perl-build
            curl -L https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm \
              > /usr/local/bin/cpanm
            chmod a+x /usr/local/bin/*
      - run:
          name: copy cpanfile and cpanfile.snapshot
          command: cp centos6/cpanfile* .
      - restore_cache:
          name: restore vanilla perl cache
          key: v1-centos6-perl
      - run:
          name: build a vanilla perl
          command: |
            [[ -f $PERL ]] || build-vanilla-perl
      - save_cache:
          name: save vanilla perl cache
          key: v1-centos6-perl
          paths:
            - /opt/vanilla-perl
      - run:
          name: install carton
          command: |
            $PERL /usr/local/bin/cpanm --notest --quiet \
              Carton App::FatPacker File::pushd ExtUtils::MakeMaker
      - run:
          command: fetch-pari
      - restore_cache:
          name: restore vanilla carton local dir
          key: v1-carton-vanilla
      - run:
          command: $PERL $CARTON install
      - save_cache:
          name: save vanilla carton local dir
          key: v1-carton-vanilla
          paths:
            - /build/centos6/local
      - run:
          name: patch Crypt::OpenPGP
          command: |
            wget -q -Olocal/cache/authors/id/S/SR/SROMANOV/Crypt-OpenPGP-1.12.tar.gz \
              http://s3.amazonaws.com/moz-devservices-bmocartons/third-party/Crypt-OpenPGP-1.15.tar.gz
      - run:
           command: $PERL $CARTON fatpack
      - run:
          name: remove vanilla perl modules
          command: rm -vfr local/lib/perl5
      - restore_cache:
          name: restore system carton local dir
          key: v1-carton-system
      - run:
          command: $SYSTEM_PERL ./vendor/bin/carton install --cached --deployment
      - save_cache:
          name: save system carton local dir
          key: v1-carton-system
          paths:
            - /build/centos6/local
      - run:
          command: package-bundle /build/centos6.tar.gz
      - store_artifacts:
          path: /build/centos6.tar.gz
          destination: ""
  # ubuntu14:
  #   working_directory: /build
  #   docker:
  #     - image: ubuntu:14.04
  #       environment: *env
  #   steps: 
  #     - checkout
  #     - run:
  #         command: cp /build/ubuntu14/mysql.list /etc/apt/sources.list.d/mysql.list
  #     - run:
  #         command: |
  #           apt-key adv --keyserver ha.pool.sks-keyservers.net \
  #             --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5
  #           apt-get update
  #           apt-get --no-install-recommends -y install \
  #             apache2 build-essential cvs g++ git graphviz libapache2-mod-perl2 \
  #             libgd-dev libgmp3-dev libmysqlclient-dev libssl-dev \
  #             mysql-client mysql-server patchutils pkg-config unzip wget

